### ISSUE TITLE
websocket API

### ISSUE THREAD

**Issue by AppWerft** [PingoUPB/PINGOWebApp#15]
Hi,
 I try to use this system at our university. My goal: using of native UI with Titanium Appcelerator. In this case I would use the backend system (with ruby) and build own apps. This apps should speak with backend over websockets (socket.io). Where I can found details about communication protocol?

**Comment by MichaelWhi** [comment]
Hi, 
sorry for the late answer, and we are happy to hear you are using PINGO and want to create apps!

There is a socket-io lib available for Titanium (https://github.com/nowelium/socket.io-titanium). On top of this, we use Juggernaut, which has a simple protocol, where each message consists of a "channel", an "event" and a "data" field (in JSON format).
There is no official documentation for the protocol, since we use it out of the box…
However, in http://socket.pingo.cc:8080/application.js at the end you can find a javascript implementation that you maybe can use within your titanium app.
For our PINGO Remote app, we use a class to send / receive messages with the three mentioned fields: https://github.com/PingoUPB/Remote-Win/blob/master/WindowsFormsApplication1/App/Helpers/JuggernautMessage.cs

Please note, that you also need to make HTTP(S) calls to the PINGO backend server, e. g. to start/stop surveys. You can find some of the API calls in our remote app: https://github.com/PingoUPB/Remote-Win/tree/master/WindowsFormsApplication1/App/Models.

Is your app for lecturers? Or students? We think for students, using a WebView in an app with some menus to select sessions, etc. would be a good solution, where you get the realtime communication over the websocket "for free".


If you want, we can also write a simple documentation listing the most important API calls plus info about how to authenticate against a PINGO server during the next days.

**Comment by AppWerft** [comment]
Hallo Michael,

wollen wir es diese Woche nochmals versuchen?

Rainer

Am 12/03/15 um 16:26 schrieb Michael Whittaker:
>
> Hi,
> sorry for the late answer, and we are happy to hear you are using 
> PINGO and want to create apps!
>
> There is a socket-io lib available for Titanium 
> (https://github.com/nowelium/socket.io-titanium). On top of this, we 
> use Juggernaut, which has a simple protocol, where each message 
> consists of a "channel", an "event" and a "data" field (in JSON format).
> There is no official documentation for the protocol, since we use it 
> out of the box…
> However, in http://socket.pingo.cc:8080/application.js at the end you 
> can find a javascript implementation that you maybe can use within 
> your titanium app.
> For our PINGO Remote app, we use a class to send / receive messages 
> with the three mentioned fields: 
> https://github.com/PingoUPB/Remote-Win/blob/master/WindowsFormsApplication1/App/Helpers/JuggernautMessage.cs
>
> Please note, that you also need to make HTTP(S) calls to the PINGO 
> backend server, e. g. to start/stop surveys. You can find some of the 
> API calls in our remote app: 
> https://github.com/PingoUPB/Remote-Win/tree/master/WindowsFormsApplication1/App/Models.
>
> Is your app for lecturers? Or students? We think for students, using a 
> WebView in an app with some menus to select sessions, etc. would be a 
> good solution, where you get the realtime communication over the 
> websocket "for free".
>
> If you want, we can also write a simple documentation listing the most 
> important API calls plus info about how to authenticate against a 
> PINGO server during the next days.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/PingoUPB/PINGOWebApp/issues/15#issuecomment-78502492>.
>

-- 
*Dipl.-Ing. Rainer Schleevoigt*
Certified TYPO3 Integrator
Certified Titanium App Developer

	Novalisweg 10
22303 Hamburg
℡ 040 60812460
|Ust-ID: DE239491976|||||||

**Comment by MichaelWhi** [comment]
Gerne, ich werde morgen früh noch mal anrufen, heute schaffe ich es leider nicht mehr

**Comment by AppWerft** [comment]
Hallo Michael,

da bin ich wieder. Gerade habe ich eine ChromeApp gebaut. Nun schliesse 
ich das USB-Teil an und hoffe, die Daten lesen zu können. Wenn mir das 
gelingt, brächte ich „nur noch“ mit PINGO zu reden. Wollen wir telefonieren?

Gruss Rainer

Am 12/03/15 um 16:26 schrieb Michael Whittaker:
>
> Hi,
> sorry for the late answer, and we are happy to hear you are using 
> PINGO and want to create apps!
>
> There is a socket-io lib available for Titanium 
> (https://github.com/nowelium/socket.io-titanium). On top of this, we 
> use Juggernaut, which has a simple protocol, where each message 
> consists of a "channel", an "event" and a "data" field (in JSON format).
> There is no official documentation for the protocol, since we use it 
> out of the box…
> However, in http://socket.pingo.cc:8080/application.js at the end you 
> can find a javascript implementation that you maybe can use within 
> your titanium app.
> For our PINGO Remote app, we use a class to send / receive messages 
> with the three mentioned fields: 
> https://github.com/PingoUPB/Remote-Win/blob/master/WindowsFormsApplication1/App/Helpers/JuggernautMessage.cs
>
> Please note, that you also need to make HTTP(S) calls to the PINGO 
> backend server, e. g. to start/stop surveys. You can find some of the 
> API calls in our remote app: 
> https://github.com/PingoUPB/Remote-Win/tree/master/WindowsFormsApplication1/App/Models.
>
> Is your app for lecturers? Or students? We think for students, using a 
> WebView in an app with some menus to select sessions, etc. would be a 
> good solution, where you get the realtime communication over the 
> websocket "for free".
>
> If you want, we can also write a simple documentation listing the most 
> important API calls plus info about how to authenticate against a 
> PINGO server during the next days.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/PingoUPB/PINGOWebApp/issues/15#issuecomment-78502492>.
>

-- 
*Dipl.-Ing. Rainer Schleevoigt*
Certified TYPO3 Integrator
Certified Titanium App Developer

	Novalisweg 10
22303 Hamburg
℡ 040 60812460
|Ust-ID: DE239491976|||||||

**Comment by heyakyra** [comment]
So there is no official server code already open source?

**Comment by MichaelWhi** [comment]
> So there is no official server code already open source?

What kind of Server Code? You are in the repository of the PINGO Server Code 🤷🏼‍♂️
This issue is very old and no information in this thread is current anymore.

**Comment by heyakyra** [comment]
Oh I see, I thought that this was just the front-end web app (in-browser) source code. Thank you! I'll give it a spin then
