### ISSUE TITLE
Regarding Real-time results

### ISSUE THREAD

**Issue by bazooka720** [PingoUPB/PINGOWebApp#18]
Wondering if there are plans of making the results (charts etc) appear real-time as audience input their information rather than when presenter clicks stop?

**Comment by MichaelWhi** [comment]
Hi! Thanks for your question and using PINGO.
We are **not** planning to implement this feature, since it can influence voter decision making and would invalidate a proper Peer Instruction design.
If students see a winning option on the chart, they tend to vote for that option regardless of what they would chose before.

**Comment by hsychla** [comment]
I always thought that this sentence from the README meant exactly that and I am just unable to get it to work...:
> Juggernaut (Github: maccman/juggernaut) and Redis (www.redis.io) optional, required for push support. Push support is enabled by default in production mode.)

My 2ct.:
While I accept the influencing problem you describe, it would be really nice from a presenter's POV to see the live number of entered votes.

**Comment by MichaelWhi** [comment]
No, push support means that any changes to the running survey or new surveys are pushed to the client's device, including synchronization of timers.

As a lecturer, you see the **number of entered votes (=number of participants**) live during voting, but do **not see the results**. 
Usually voting is only enabled for 30 seconds to a few minutes, so in this use case there would be no big benefit of seeing the results earlier. Please confer to https://www.amazon.com/Peer-Instruction-Manual-Eric-Mazur/dp/0135654416, this design setting is the underlying idea for PINGO.

**Comment by bazooka720** [comment]
Thanks Michael:

I noticed that the version you have on Github is on older version of Ruby.
Are there any issues if we upgrade to latest version? Do you have a repo
with latest ruby version?

Thanks,
VC

**Comment by MichaelWhi** [comment]
We are currently preparing a new release with updated libraries and a newer Ruby version. 

In the meantime, feel free to use a newer Ruby-Version, we tried some 2.x-versions without issues. However, we cannot guarantee that the performance is the same as with the battle-tested 1.9.3.

**Comment by bazooka720** [comment]
Thanks so much!

Any chance I can get access the the new release? We are looking to
self-host on a server and would be great to go with the latest

**Comment by MichaelWhi** [comment]
> Any chance I can get access the the new release?

Sorry, we are not yet finished with the upgrading process. 
We will release the version as soon, as it is completed, on GitHub, but that might take a few days or weeks.

**Comment by yawar-ali** [comment]
@MichaelWhi I am trying to set the PINGO but found that `ruby-standard-deviation` is not available should I use `ruby_native_statistics` instead will it work without any issue ?

Also, Can you elaborate a bit on Push Support I am a lil confused there ?

**Comment by MichaelWhi** [comment]
Hi @sweetevil,

in the Gemfile, please replace the line
`gem 'ruby-standard-deviation'`
with
`gem 'ruby-standard-deviation', git: "git://github.com/PingoUPB/ruby-standard-deviation.git" `

Now bundling should work!

Regarding push support, I've left a comment in https://github.com/PingoUPB/PINGOWebApp/issues/18#issuecomment-335428544. It is a PubSub-Server so clients get notified about changes.

Again, as you can read in this thread, it might be better for you if you start with the upcoming release. Otherwise, you might need to re-setup PINGO, because the new version will have changes regarding the PubSub-server and the Database server.
For the current version, everything in the README is still working; the current version uses Juggernaut (based on Socket.IO) as its PubSub-Backend and is production-ready.

If you have any concrete questions, feel free to ask.

Info about the general PNGO architecture can be seen in the README and in most of our publications about PINGO.

**Comment by bazooka720** [comment]
hi...just following-up about the newer release you were planning sometime back. Any update on when it might be done?

**Comment by NMarkgraf** [comment]
Mid 2020 and still no response ... seems to me, pingo development is ceased .. :-(.

**Comment by arthurzenika** [comment]
I think real time results can be used for other settings and be useful. For example for icebreakers where you ask how the audience is feeling and you have an evolving word cloud to display to the participants. This could be an option, thus keeping the "don't influence a vote" approach the default.
