### ISSUE TITLE
bundle install failing (broken dependency 'ruby-standard-deviation')

### ISSUE THREAD

**Issue by bnwe** [PingoUPB/PINGOWebApp#20]
Running `bundle install` fails, because `ruby-standard-deviation` seems to be yanked from rubygems.org. It seems to be here now: https://github.com/jtescher/descriptive-statistics.

**Comment by MichaelWhi** [comment]
Hi! 

Sorry for the late answer... we are currently busy testing the new PINGO release based on Rails 5.

You can try the [rails51](https://github.com/PingoUPB/PINGOWebApp/tree/rails51) branch (with some upgrades bugs, that have been fixed but are still in testing, they'll be pushed soon), wait for the Rails 5 release in master or - in the meantime - can simply comment out the gem in the Gemfile. It is not in use anymore, anyways.

For production use I recommend you to wait for the release. For development purposes you can use the current master without the yanked gem, since the HTTP API and most of the internal api stays the same.
